config/routes.rb
Rails.application.routes.draw do
  get 'index/termino'
  get 'page/index'
  resources :electric_cars
  devise_for :users
  get 'home/page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#page"
end

app/models/electric_car.rb
class ElectricCar < ApplicationRecord
   # before_action :authenticate_user!

    belongs_to :user
    has_and_belongs_to_many :features
    has_many :comments
    validates :model, presence: true, uniqueness: true
    validates :brand, presence: true
    validates :manufacture_year, presence: true
    validates :driving_range, presence: true
    validates :rental_price, presence: true

    enum brand: [:tesla, :nissan, :chevrolet, :bmw, :audi, :hyundai, :kia, :ford, :porsche, :volkswagen]
    enum features: [:bateria_iones_litio, :bateria_estado_solido, :sistema_carga_inalambrica, :sistema_carga_alambrica, :tecnologia_asistencia_conduccion ]
end

app/controllers/electric_cars_controller.rb
class ElectricCarsController < ApplicationController
  before_action :set_electric_car, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  #before_action only: [:edit, :update, :create, :destroy] do
   # authorize_request(["admin"])
  #before_action :require_admin, only: %i[ new create edit update destroy ]

  # GET /electric_cars or /electric_cars.json
  def index
    @electric_cars = ElectricCar.all
    @pagy, @electric_cars = pagy(ElectricCar.ransack(params[:q]).result)
    @ransack = ElectricCar.ransack(params[:q])
    
    
    end

  # GET /electric_cars/1 or /electric_cars/1.json
  def show
   @electric_car = ElectricCar.find(params[:id])
  end

  # GET /electric_cars/new
  def new
    @electric_car = ElectricCar.new
  end

  # GET /electric_cars/1/edit
  def edit
  end

  # POST /electric_cars or /electric_cars.json
  def create
    @electric_car = ElectricCar.new(electric_car_params)

    respond_to do |format|
      if @electric_car.save
        format.html { redirect_to electric_car_url(@electric_car), notice: "Electric car was successfully created." }
        format.json { render :show, status: :created, location: @electric_car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @electric_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /electric_cars/1 or /electric_cars/1.json
  def update
    respond_to do |format|
      if @electric_car.update(electric_car_params)
        format.html { redirect_to electric_car_url(@electric_car), notice: "Electric car was successfully updated." }
        format.json { render :show, status: :ok, location: @electric_car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @electric_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /electric_cars/1 or /electric_cars/1.json
  def destroy
    @electric_car.destroy

    respond_to do |format|
      format.html { redirect_to electric_cars_url, notice: "Electric car was successfully destroyed." }
      format.json { head :no_content }
    end
  end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_electric_car
      @electric_car = ElectricCar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def electric_car_params
      params.require(:electric_car).permit(:model, :brand, :features, :manufacture_year, :driving_range, :rental_price, :image)
    end

    #def require_admin
      #unless current_user && current_user.admin?
       # redirect_to root_path
    #  end
   # end
  

app/helpers/electric_cars_helper.rb
module ElectricCarsHelper
end

app/views/electric_cars/_electric_car.html.erb
<div id="<%= dom_id electric_car %>">
  <p>
    <strong>Model:</strong>
    <%= electric_car.model %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= electric_car.brand %>
  </p>

  <p>
    <strong>Features:</strong>
    <%= electric_car.features %>
  </p>

  <p>
    <strong>Manufacture year:</strong>
    <%= electric_car.manufacture_year %>
  </p>

  <p>
    <strong>Driving range:</strong>
    <%= electric_car.driving_range %>
  </p>

  <p>
    <strong>Rental price:</strong>
    <%= electric_car.rental_price %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= image_tag electric_car.image, with:"20%" %>
    <%else%>
    <img src="https://unsplash.com/es/s/fotos/autos/40x40" alt= "avatar", width="20%">
  </p>
<%end%>
</div>

app/views/electric_cars/_form.html.erb
<%= form_with(model: electric_car) do |form| %>
  <% if electric_car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(electric_car.errors.count, "error") %> prohibited this electric_car from being saved:</h2>

      <ul>
        <% electric_car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.label :features, style: "display: block" %>
    <%= form.text_area :features %>
  </div>

  <div>
    <%= form.label :manufacture_year, style: "display: block" %>
    <%= form.number_field :manufacture_year %>
  </div>

  <div>
    <%= form.label :driving_range, style: "display: block" %>
    <%= form.number_field :driving_range %>
  </div>

  <div>
    <%= form.label :rental_price, style: "display: block" %>
    <%= form.text_field :rental_price %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/electric_cars/edit.html.erb
<h1>Editing electric car</h1>

<%= render "form", electric_car: @electric_car %>

<br>

<div>
  <%= link_to "Show this electric car", @electric_car %> |
  <%= link_to "Back to electric cars", electric_cars_path %>
</div>

app/views/electric_cars/index.html.erb
<div id="electric_cars">
  <h1>Electric cars</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Model</th>
        <th scope="col">Marca</th>
        <th scope="col">Año de fabricación</th>
        <th scope="col">Photo</th>
      </tr>
    </thead>
    <tbody>
      <% @electric_cars.each do |electric_car| %>
        <%= render electric_car %>
        <p>
          <%= link_to "Show this electric car", electric_car %>
        </p>
      <% end %>
    </tbody>
  </table>
</div>
<%= pagy_nav(@pagy) if @pagy.pages > 1 %>
<%= link_to "New electric car", new_electric_car_path %>

app/views/electric_cars/new.html.erb
<h1>New electric car</h1>

<%= render "form", electric_car: @electric_car %>

<br>

<div>
  <%= link_to "Back to electric cars", electric_cars_path %>
</div>

app/views/electric_cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @electric_car %>

<div>
  <%= link_to "Edit this electric car", edit_electric_car_path(@electric_car) %> |
  <%= link_to "Back to electric cars", electric_cars_path %>

  <%= button_to "Destroy this electric car", @electric_car, method: :delete %>
</div>