config/routes.rb
Rails.application.routes.draw do
  get 'index/termino'
  get 'page/index'
  resources :electric_cars
  devise_for :users
  get 'home/page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#page"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :electric_cars
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :electric_car
end

app/models/electric_car.rb
class ElectricCar < ApplicationRecord
   # before_action :authenticate_user!

    belongs_to :user
    has_and_belongs_to_many :features
    has_many :comments
    validates :model, presence: true, uniqueness: true
    validates :brand, presence: true
    validates :manufacture_year, presence: true
    validates :driving_range, presence: true
    validates :rental_price, presence: true

    enum brand: [:tesla, :nissan, :chevrolet, :bmw, :audi, :hyundai, :kia, :ford, :porsche, :volkswagen]
    enum features: [:bateria_iones_litio, :bateria_estado_solido, :sistema_carga_inalambrica, :sistema_carga_alambrica, :tecnologia_asistencia_conduccion ]
end

app/models/electric_cars_feature.rb
class ElectricCarsFeature < ApplicationRecord
  belongs_to :electric_cars
  belongs_to :feature
end

app/models/feature.rb
class Feature < ApplicationRecord
end

app/models/operation_type.rb
class OperationType < ApplicationRecord
    belongs_to :user
    belongs_to :electric_car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         enum role: [:client,  :admin]

         validates :email, presence: true
         validates :password, presence: true
    belongs_to :admin, optional: true, class_name: "User"
    has_many :electric_cars
    
  after_initialize :set_default_role, if: :new_record?
    def set_default_role
    self.role ||= :admin
  end  
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include Pagy::Backend
     def authorize_request(kind = nil)
        unless kind.include?(current_user.role)
            redirect_to home_page_path, notice: "Tu no estas autorizado para ingresar en esta area"
        end
    end
end

app/controllers/electric_cars_controller.rb
class ElectricCarsController < ApplicationController
  before_action :set_electric_car, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  #before_action only: [:edit, :update, :create, :destroy] do
   # authorize_request(["admin"])
  #before_action :require_admin, only: %i[ new create edit update destroy ]

  # GET /electric_cars or /electric_cars.json
  def index
    @electric_cars = ElectricCar.all
    @pagy, @electric_cars = pagy(ElectricCar.ransack(params[:q]).result)
    @ransack = ElectricCar.ransack(params[:q])
    
    
    end

  # GET /electric_cars/1 or /electric_cars/1.json
  def show
   @electric_car = ElectricCar.find(params[:id])
  end

  # GET /electric_cars/new
  def new
    @electric_car = ElectricCar.new
  end

  # GET /electric_cars/1/edit
  def edit
  end

  # POST /electric_cars or /electric_cars.json
  def create
    @electric_car = ElectricCar.new(electric_car_params)

    respond_to do |format|
      if @electric_car.save
        format.html { redirect_to electric_car_url(@electric_car), notice: "Electric car was successfully created." }
        format.json { render :show, status: :created, location: @electric_car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @electric_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /electric_cars/1 or /electric_cars/1.json
  def update
    respond_to do |format|
      if @electric_car.update(electric_car_params)
        format.html { redirect_to electric_car_url(@electric_car), notice: "Electric car was successfully updated." }
        format.json { render :show, status: :ok, location: @electric_car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @electric_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /electric_cars/1 or /electric_cars/1.json
  def destroy
    @electric_car.destroy

    respond_to do |format|
      format.html { redirect_to electric_cars_url, notice: "Electric car was successfully destroyed." }
      format.json { head :no_content }
    end
  end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_electric_car
      @electric_car = ElectricCar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def electric_car_params
      params.require(:electric_car).permit(:model, :brand, :features, :manufacture_year, :driving_range, :rental_price, :image)
    end

    #def require_admin
      #unless current_user && current_user.admin?
       # redirect_to root_path
    #  end
   # end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def termino
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/electric_cars_helper.rb
module ElectricCarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/index/termino.html.erb
</div class="container mt-5">
<h1 class= "text-center">Termino y Condiciones</h1>

<p>Al registrarte y utilizar EcoDrive, aceptas automáticamente estos Términos y Condiciones en su totalidad. Si no estás de acuerdo con alguno de los términos establecidos, te recomendamos que no utilices nuestra plataforma.</p>

        <h4>2. Uso de la Plataforma</h4>
        <p>...</p>

        <h4>3. Contenido del Usuario</h4>
        <p>...</p>

        <h4>4. Privacidad</h4>
        <p>La privacidad de nuestros usuarios es importante para nosotros. Nuestra <a href="#">Política de Privacidad</a> describe cómo recopilamos, usamos y compartimos la información que recopilamos de nuestros usuarios. Al utilizar JetMaintain, aceptas nuestras prácticas de privacidad, por lo que te recomendamos revisar nuestra Política de Privacidad.</p>

        <h4>5. Cambios en los Términos y Condiciones</h4>
        <p>Eco Drive se reserva el derecho de modificar o actualizar estos Términos y Condiciones en cualquier momento y sin previo aviso. Se te notificará cualquier cambio a través de una notificación en la plataforma o por correo electrónico. Te recomendamos revisar regularmente estos términos para estar al tanto de las actualizaciones.</p>

        <h4>6. Terminación de la Cuenta</h4>
        <p>...</p>

        <h4>7. Contacto</h4>
        <p>Si tienes alguna pregunta o comentario sobre estos Términos y Condiciones, puedes ponerte en contacto con nosotros a través de la información de contacto proporcionada en la plataforma.</p>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecodrive</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class= "container">
   <p class="notice"><%= notice %></p>
   
    <%= yield %>

  </div>





    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>

app/views/page/index.html.erb
</div class= "container mt-5" >
<h1 class="text-center">Acerca de Nosotros</h1>
<hr>

<p class= "text-center">esomos una organizacion dedicada a satisfacers las 
necesidades y gustos de los clientes
explore y encuentre lo mas modernos y exclusivos modelos para 
el disfrute de usted y su familia</p>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Eco Drive</a>
        </li>
      <li class="nav-item">
          <%= link_to "Acerca de Nosotros", page_index_path ,class:"nav-link"%>
        </li>
             </li>
        <li class="nav-item">
          <%= link_to "Terminos & Condiciones", index_termino_path ,class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Electric_Cars", electric_cars_path ,class:"nav-link"%>
        </li>
        
      </ul>

        <ul class="navbar-nav ms-auto mb-5 mb-lg-0">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <% if user_signed_in? %> 
            <%= current_user.role %>    
            <% else %> Registrate o conectate 
          <% end %> </a>
          <ul class="dropdown-menu">
          <% if user_signed_in? %>
              <li>
              <%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item',method: :delete %>
              </li>
              <li>
              <%= link_to 'Editar Perfil', edit_user_registration_path, class: 'dropdown-item'%>
              </li>
           
            <% else %> 
              <li>
              <%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%>
              </li>
              <li>
              <hr class="dropdown-divider">
              </li>
            <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%> </li><% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>





























   